FIND_PATH(CUBA_INCLUDE_DIR cuba.h PATHS $ENV{HOME}/usr/include $ENV{HOME}/usr/include/cuba )

FIND_LIBRARY(CUBA_LIBRARY NAMES cuba PATHS $ENV{HOME}/usr/lib ) 


IF (CUBA_INCLUDE_DIR)
   SET(CUBA_FOUND TRUE)
ENDIF (CUBA_INCLUDE_DIR)


IF (CUBA_FOUND)
   IF (NOT Cuba_FIND_QUIETLY)
      MESSAGE(STATUS "Found cuba: ${CUBA_LIBRARY}")
   ENDIF (NOT Cuba_FIND_QUIETLY)
ELSE (CUBA_FOUND)
   IF (Cuba_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find cuba")
   ENDIF (Cuba_FIND_REQUIRED)
ENDIF (CUBA_FOUND)
